---
# tasks file for hpoo
- name: SQL Query
  shell: |    
    sqlcmd -S {{ server }} -U {{ user }} -P {{ password }} -d {{ database }} -i "hpoo/files/services.sql"
  register: result

- debug: 
    msg: "{{ result.json | list }}"