---
- name: Recursively remove directory
  file:
    path: "{{ base_dir }}/{{ item }}"
    state: absent
  with_items:
    - "output"
    #- "data"

- name: Create Directories
  file:
    path: "{{ base_dir }}/{{ item }}"
    state: directory
    recurse: yes
    owner: 1000
    group: 1000
    mode: 0775
  with_items:
    - "output"
    #- "data"

#    sqlcmd -S {{ server }} -U {{ user }} -P {{ password }} -d {{ database }} -i "hpoo/files/services.sql" -o "{{ base_dir }}/output/result.txt"
# tasks file for hpoo
- name: SQL Query
  shell: |
    sqlcmd -S {{ server }} -U {{ user }} -P {{ password }} -d {{ database }} -i "hpoo/files/services.sql" -o "{{ base_dir }}/output/mydata.csv" -h-1 -s"," -w 700
  register: result

# - name: transform
#   shell: |    
#     cat "{{ base_dir }}/output/result.txt" | jq -Rs '{"data": [split("\n") | map(select(length > 0))[] | split(" +";"g") | {"{#ServiceName}": .[0], "{#ServiceStatus}": .[1], "{#StatusDateTime}": .[2], "{#ServerName}": .[3], "{#PhysicalSrverName}": .[4]}]}'

- name: copy the output to a local file
  copy:
    content: "{{ result.stdout }}"
    dest: "{{ base_dir }}/output/result.txt"
  delegate_to: localhost

- name: Transform01
  shell: |
    cat /var/output/mydata.csv | tr -d " " > /var/output/mydata2.csv

- name: Transform02
  shell: |
    sed -i -e '1iServiceName,ServiceStatus,StatusDateTime,ServerName,PhysicalSrverName' /var/output/mydata2.csv

- name: Transform03
  shell: |
    mlr --c2j --jlistwrap cat /var/output/mydata2.csv > /var/output/mydata3.json


# - name: read
#   shell: |
#     cat "{{ base_dir }}/output/result.txt"
#   register: result02

# - name: show
#   debug:
#     msg: "{{ result02.stdout }}"

# - name: Copy file with owner and permissions
#   copy:
#     src: result
#     dest: "{{ base_dir }}/output/result.json"
#     owner: 1000
#     group: 1000
#     mode: '0644'
